using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework;

#if XNA_BUILD
namespace DwarfCorp.Gui.Input
{
    /// <summary>
    /// Translates windows keyboard messages into a form consumable by the GUI.
    /// </summary>
    public class GumInputMapper
    {
        public enum WindowMessage
        {
            WM_KEYDOWN = 0x100,
            WM_KEYUP = 0x101,
            WM_CHAR = 0x102,

            WM_MOUSEMOVE = 0x0200,
            WM_LBUTTONDOWN = 0x0201,
            WM_LBUTTONUP = 0x202,
            WM_RBUTTONDOWN = 0x204,
            WM_RBUTTONUP = 0x0205,

            WM_MOUSEWHEEL = 0x020A
        };

        // Need a thread-safe queue of events, since these are generated by the windows message pump.

        public class QueuedInput
        {
            public Gui.InputEvents Message;
            public Gui.InputEventArgs Args;
        }

        public global::System.Threading.Mutex QueueLock = new global::System.Threading.Mutex();
        public List<QueuedInput> Queued = new List<QueuedInput>();

        private bool CtrlDown = false;
        private bool AltDown = false;
        private bool ShiftDown = false;
        private bool ConsoleTogglePressed = false;

        public bool WasConsoleTogglePressed()
        {
            if (ConsoleTogglePressed)
            {
                ConsoleTogglePressed = false;
                return true;
            }
            return false;
        }

        public List<QueuedInput> GetInputQueue()
        {
            QueueLock.WaitOne();
            var r = Queued;
            Queued = new List<QueuedInput>();
            QueueLock.ReleaseMutex();
            return r;
        }

        public GumInputMapper(IntPtr WindowHandle)
        {
            MessageFilter.AddMessageFilter((c) => HandleEvent(c));
        }

        private global::System.Windows.Forms.Keys TranslateKey(IntPtr LParam, global::System.Windows.Forms.Keys Key)
        {
            var extended = ((int)LParam & 0x01000000) != 0;
            var realCode = Key;
            if (realCode == global::System.Windows.Forms.Keys.ControlKey)
                realCode = extended ? global::System.Windows.Forms.Keys.RControlKey : global::System.Windows.Forms.Keys.LControlKey;
            if (realCode == global::System.Windows.Forms.Keys.ShiftKey)
            {
                //Grab the scan code from LParam... Who would have thought just telling 
                // left and right shift apart would be such a PITA?
                var scanCode = ((int)LParam & 0xff0000) >> 16;
                if (scanCode == 42) return global::System.Windows.Forms.Keys.LShiftKey;
                if (scanCode == 54) return global::System.Windows.Forms.Keys.RShiftKey;
                throw new InvalidOperationException();
            }
            return realCode;
        }

        private bool _disableInput = false;
        private bool HandleEvent(global::System.Windows.Forms.Message Msg)
        {
            if (!GameStates.GameState.Game.IsActive)
            {
                _disableInput = true;
                return false;
            }

            if (_disableInput)
            {
                _disableInput = false;
                return false;
            }
            QueueLock.WaitOne();
            bool handled = false;

            switch ((WindowMessage)Msg.Msg)
            {
                case WindowMessage.WM_CHAR:
                    {
                        var args = new global::System.Windows.Forms.KeyPressEventArgs((char)Msg.WParam);
                        Queued.Add(new QueuedInput
                        {
                            Message = Gui.InputEvents.KeyPress,
                            Args = new Gui.InputEventArgs
                            {
                                KeyValue = args.KeyChar,
                                Alt = false,
                                Control = false,
                                Shift = false,
                            }
                        });
                        handled = true;
                        break;
                    }
                case WindowMessage.WM_KEYDOWN:
                    {
                        var args = new global::System.Windows.Forms.KeyEventArgs((global::System.Windows.Forms.Keys)Msg.WParam);
                        
                        if (args.KeyData == global::System.Windows.Forms.Keys.Alt)
                            AltDown = true;
                        if (args.KeyData == global::System.Windows.Forms.Keys.ControlKey)
                            CtrlDown = true;
                        if (args.KeyData == global::System.Windows.Forms.Keys.ShiftKey)
                            ShiftDown = true;

                        var realCode = TranslateKey(Msg.LParam, args.KeyCode);

                        if (realCode == global::System.Windows.Forms.Keys.Oemtilde)
                        {
                            ConsoleTogglePressed = true;
                        }
                        else
                        {
                            Queued.Add(new QueuedInput
                            {
                                Message = Gui.InputEvents.KeyDown,
                                Args = new Gui.InputEventArgs
                                {
                                    Alt = args.Alt,
                                    Control = args.Control,
                                    Shift = args.Shift,
                                    KeyValue = (int)realCode,
                                }
                            });
                        }

                        handled = true;
                        break;
                    }
                case WindowMessage.WM_KEYUP:
                    {
                        var args = new global::System.Windows.Forms.KeyEventArgs((global::System.Windows.Forms.Keys)Msg.WParam);

                        if (args.KeyData == global::System.Windows.Forms.Keys.Alt)
                            AltDown = false;
                        if (args.KeyData == global::System.Windows.Forms.Keys.ControlKey)
                            CtrlDown = false;
                        if (args.KeyData == global::System.Windows.Forms.Keys.ShiftKey)
                            ShiftDown = false;
                        
                        var realCode = TranslateKey(Msg.LParam, args.KeyCode);

                        Queued.Add(new QueuedInput
                        {
                            Message = Gui.InputEvents.KeyUp,
                            Args = new Gui.InputEventArgs
                            {
                                Alt = args.Alt,
                                Control = args.Control,
                                Shift = args.Shift,
                                KeyValue = (int)args.KeyCode
                            }
                        });
                        handled = true;
                        break;
                    }
                case WindowMessage.WM_LBUTTONDOWN:
                case WindowMessage.WM_RBUTTONDOWN:
                    {
                        Queued.Add(new QueuedInput
                        {
                            Message = Gui.InputEvents.MouseDown,
                            Args = new Gui.InputEventArgs
                            {
                                Alt = AltDown,
                                Control = CtrlDown,
                                Shift = ShiftDown,
                                MouseButton = (WindowMessage)Msg.Msg == WindowMessage.WM_LBUTTONDOWN ? 0 : 1,
                                X = (int)((int)Msg.LParam & 0x0000FFFFu),
                                Y = (int)((int)Msg.LParam & 0xFFFF0000u) >> 16
                            }
                        });
                        handled = false;
                        break;
                    }
                case WindowMessage.WM_LBUTTONUP:
                case WindowMessage.WM_RBUTTONUP:
                    {
                        Queued.Add(new QueuedInput
                        {
                            Message = Gui.InputEvents.MouseUp,
                            Args = new Gui.InputEventArgs
                            {
                                Alt = AltDown,
                                Control = CtrlDown,
                                Shift = ShiftDown,
                                MouseButton = (WindowMessage)Msg.Msg == WindowMessage.WM_LBUTTONUP ? 0 : 1,
                                X = (int)((int)Msg.LParam & 0x0000FFFFu),
                                Y = (int)((int)Msg.LParam & 0xFFFF0000u) >> 16
                            }
                        });
                        Queued.Add(new QueuedInput
                        {
                            Message = Gui.InputEvents.MouseClick,
                            Args = new Gui.InputEventArgs
                            {
                                Alt = AltDown,
                                Control = CtrlDown,
                                Shift = ShiftDown,
                                MouseButton = (WindowMessage)Msg.Msg == WindowMessage.WM_LBUTTONUP ? 0 : 1,
                                X = (int)((int)Msg.LParam & 0x0000FFFFu),
                                Y = (int)((int)Msg.LParam & 0xFFFF0000u) >> 16
                            }
                        });
                        handled = false;
                        break;
                    }
                case WindowMessage.WM_MOUSEMOVE:
                    {
                        Queued.Add(new QueuedInput
                        {
                            Message = Gui.InputEvents.MouseMove,
                            Args = new Gui.InputEventArgs
                            {
                                Alt = AltDown,
                                Control = CtrlDown,
                                Shift = ShiftDown,
                                X = (int)((int)Msg.LParam & 0x0000FFFFu),
                                Y = (int)((int)Msg.LParam & 0xFFFF0000u) >> 16
                            }
                        });
                        handled = false;
                        break;
                    }
                case WindowMessage.WM_MOUSEWHEEL:
                {
                    Queued.Add(new QueuedInput
                    {
                        Message = Gui.InputEvents.MouseWheel,
                        Args = new Gui.InputEventArgs
                        {
                            Alt = AltDown,
                            Control = CtrlDown,
                            Shift = ShiftDown,
                            ScrollValue = (short)((Msg.WParam.ToInt32() & 0xFFFF0000u) >> 16)
                        }
                    });
                    handled = false;
                    break;
                }
                default:
                    handled = false;
                    break;
            }

            QueueLock.ReleaseMutex();
            return handled;
        }

    }
}
#endif