//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DwarfCorp {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class AssetSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AssetSettings defaultInstance = ((AssetSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AssetSettings())));
        
        public static AssetSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string TileSet {
            get {
                return ((string)(this["TileSet"]));
            }
            set {
                this["TileSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string DwarfSheet {
            get {
                return ((string)(this["DwarfSheet"]));
            }
            set {
                this["DwarfSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string InteriorSheet {
            get {
                return ((string)(this["InteriorSheet"]));
            }
            set {
                this["InteriorSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string GUISheet {
            get {
                return ((string)(this["GUISheet"]));
            }
            set {
                this["GUISheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string GoblinSheet {
            get {
                return ((string)(this["GoblinSheet"]));
            }
            set {
                this["GoblinSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string IconSheet {
            get {
                return ((string)(this["IconSheet"]));
            }
            set {
                this["IconSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int DwarfSheet_tilewidth {
            get {
                return ((int)(this["DwarfSheet_tilewidth"]));
            }
            set {
                this["DwarfSheet_tilewidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int DwarfSheet_tileHeight {
            get {
                return ((int)(this["DwarfSheet_tileHeight"]));
            }
            set {
                this["DwarfSheet_tileHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int TileSet_tileWidth {
            get {
                return ((int)(this["TileSet_tileWidth"]));
            }
            set {
                this["TileSet_tileWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int TileSet_tileHeight {
            get {
                return ((int)(this["TileSet_tileHeight"]));
            }
            set {
                this["TileSet_tileHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int InteriorSheet_tileWidth {
            get {
                return ((int)(this["InteriorSheet_tileWidth"]));
            }
            set {
                this["InteriorSheet_tileWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int InteriorSheet_tileHeight {
            get {
                return ((int)(this["InteriorSheet_tileHeight"]));
            }
            set {
                this["InteriorSheet_tileHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int GoblinSheet_tileWidth {
            get {
                return ((int)(this["GoblinSheet_tileWidth"]));
            }
            set {
                this["GoblinSheet_tileWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int GoblinSheet_tileHeight {
            get {
                return ((int)(this["GoblinSheet_tileHeight"]));
            }
            set {
                this["GoblinSheet_tileHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string ResourceSheet {
            get {
                return ((string)(this["ResourceSheet"]));
            }
            set {
                this["ResourceSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int ResourceSheet_tileWidth {
            get {
                return ((int)(this["ResourceSheet_tileWidth"]));
            }
            set {
                this["ResourceSheet_tileWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int ResourceSheet_tileHeight {
            get {
                return ((int)(this["ResourceSheet_tileHeight"]));
            }
            set {
                this["ResourceSheet_tileHeight"] = value;
            }
        }
    }
}
