//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DwarfCorp {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ControlSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ControlSettings defaultInstance = ((ControlSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ControlSettings())));
        
        public static ControlSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::Microsoft.Xna.Framework.Input.Keys Forward {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Forward"]));
            }
            set {
                this["Forward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::Microsoft.Xna.Framework.Input.Keys Left {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Left"]));
            }
            set {
                this["Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public global::Microsoft.Xna.Framework.Input.Keys Right {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Right"]));
            }
            set {
                this["Right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::Microsoft.Xna.Framework.Input.Keys Back {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Back"]));
            }
            set {
                this["Back"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LeftShift")]
        public global::Microsoft.Xna.Framework.Input.Keys CameraMode {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["CameraMode"]));
            }
            set {
                this["CameraMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public global::Microsoft.Xna.Framework.Input.Keys GodMode {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["GodMode"]));
            }
            set {
                this["GodMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z")]
        public global::Microsoft.Xna.Framework.Input.Keys TimeForward {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["TimeForward"]));
            }
            set {
                this["TimeForward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X")]
        public global::Microsoft.Xna.Framework.Input.Keys TimeBackward {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["TimeBackward"]));
            }
            set {
                this["TimeBackward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PageUp")]
        public global::Microsoft.Xna.Framework.Input.Keys SliceUp {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["SliceUp"]));
            }
            set {
                this["SliceUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PageDown")]
        public global::Microsoft.Xna.Framework.Input.Keys SliceDown {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["SliceDown"]));
            }
            set {
                this["SliceDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public global::Microsoft.Xna.Framework.Input.Keys Pause {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Pause"]));
            }
            set {
                this["Pause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("O")]
        public global::Microsoft.Xna.Framework.Input.Keys OrderScreen {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["OrderScreen"]));
            }
            set {
                this["OrderScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public global::Microsoft.Xna.Framework.Input.Keys Map {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Map"]));
            }
            set {
                this["Map"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q")]
        public global::Microsoft.Xna.Framework.Input.Keys SliceSelected {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["SliceSelected"]));
            }
            set {
                this["SliceSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public global::Microsoft.Xna.Framework.Input.Keys SliceSelectedUp {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["SliceSelectedUp"]));
            }
            set {
                this["SliceSelectedUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public global::Microsoft.Xna.Framework.Input.Keys ToggleGUI {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["ToggleGUI"]));
            }
            set {
                this["ToggleGUI"] = value;
            }
        }
    }
}
